Customer_ID= "Customer ID"n;
Label Customer_ID='Customer ID';
drop "Customer ID"n;
Membership_Type= "Membership Type"n;
Label Membership_Type='Membership Type';
drop "Membership Type"n;
Total_Spend= "Total Spend"n;
Label Total_Spend='Total Spend';
drop "Total Spend"n;
Items_Purchased= "Items Purchased"n;
Label Items_Purchased='Items Purchased';
drop "Items Purchased"n;
Average_Rating= "Average Rating"n;
Label Average_Rating='Average Rating';
drop "Average Rating"n;
Discount_Applied= "Discount Applied"n;
Label Discount_Applied='Discount Applied';
drop "Discount Applied"n;
Days_Since_Last_Purchase= "Days Since Last Purchase"n;
Label Days_Since_Last_Purchase='Days Since Last Purchase';
drop "Days Since Last Purchase"n;
Satisfaction_Level= "Satisfaction Level"n;
Label Satisfaction_Level='Satisfaction Level';
drop "Satisfaction Level"n;
